import type { Metadata } from "next";
import { Nunito, Pacifico } from "next/font/google";
import "../globals.css";
import { Header } from "@/components/shared/header";

export const metadata: Metadata = {
  title: "Next App | Главная",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen">
      <Header />
      {children}
    </main>
  );
}
