import type { Metadata } from "next";
import { Nunito, Pacifico } from "next/font/google";
import "../globals.css";
import { Header } from "@/components/shared/header";

const nunito = Nunito({
  variable: "--font-nunito",
  weight: ["400", "500", "600", "700", "800", "900"],
});

const dancing = Pacifico({
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <main className="min-h-screen bg-sky-500">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
